version: '2.1'

services:
  titan-angular:
    image: titan-angular
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4300:4300
    ## set your startup file here
    command: node --inspect index.js